### ISSUE TITLE
disable no-confusing-arrow

### ISSUE THREAD

**Issue by einarlove** [unfold/eslint-config#35]
Allow `bool => bool ? 'a' : 'b'`instead of writing
```
bool => {
  if (bool) {
    return 'a'
  }
  return 'b'
}
```

Always bugged me, but since I'm not allowed to 
```js
const MemberPhotoImg = styled.img`
  width: 100%;
  height: 100%;
  display: ${props => props.src ? 'block' : 'none'};
`
```
without wiriting disables everywhere, I think we should disable it.

**Comment by simenbrekken** [comment]
Can't you wrap it in parenthesis? `display: ${props => (props.src ? 'block' : 'none')};`

**Comment by simenbrekken** [comment]
:shipit:

**Comment by einarlove** [comment]
I'll wait a bit with this and try using wrapping them in parens and see how I feel about it
```
/*eslint no-confusing-arrow: ["error", {"allowParens": true}]*/
/*eslint-env es6*/
var x = a => (1 ? 2 : 3);
var x = (a) => (1 ? 2 : 3);
```
